### ISSUE TITLE
Update Italian language

### ISSUE THREAD

**Issue by nos3000** [chrisheib/NWO-Donation-Monitor#4]
Hello, I know a lot of Italian people interested in this software, but they are discouraged from using it because they have to log in with Neverwinter in English or German to use the program. It would be nice to add Italian.

**Comment by chrisheib** [comment]
Hey there, thanks alot for trying it out. 
Can you send me a few logs from an Italian version? The more, the merrier. 
I need to adapt the program to handle the correct Dates and any special characters that might occur.
Please note that the program does not support logs from multiple languages at once, so if you import from one game language, you should stick to it.

**Comment by nos3000** [comment]
I can send you a translation:

Heroic Shard of Power = Frammento di potere eroico
Adventurer's Shard of Power = Frammento di potere dell'avventuriero
Dungeoneer's Shard of Power =Frammento di potere dell'esploratore di dungeon
Conqueror's Shard of Power = Franteo di potere del conquistatore
Wood = Legno
Stone = Pietra
Metal = Metallo
Food = Cibo
Professions Supplies = Provviste per Mestieri
Gold = Oro
Glory = Gloria
Gems = Gemme
Surplus Equipment = Equipaggiamento extra
Astral Diamond Chests = Scrigni di diamanti astrali
Treasures of Tyranny = Tesori della tirannia
Frozen Treasures = Tesori ghiacciati
Fey Trinkets = Gingilli fatati
Dark Gifts = Regali oscuri
Influence = Influenza


if you have an email I can send you file.csv in Italian

**Comment by chrisheib** [comment]
For now I only need the file, feel free to send it at chrisheib@gmx.de

**Comment by chrisheib** [comment]
Should be implemented with 056bfb2.

**Comment by nos3000** [comment]
thank you very much friend, it works great
